name: built_dorm
version: 1.0.46
author: Frank Pepermans <frank@igindo.com>
description: "[Deprecated library] - please use other ORM libraries on pub"
homepage: https://github.com/frankpepermans/dorm
documentation: http://igindo.com/dart/dorm/index.html
environment:
  sdk: '>=2.0.0-dev.62.0 <3.0.0'
dev_dependencies:
  analyzer: ^0.32.0
  build: ^0.12.0
  source_gen: ^0.8.0
  build_runner: ^0.8.7
  test: ^0.12.0
  benchmark_harness: ^1.0.0